[phases.setup]
dependsOn = []
aptPkgs = ["google-chrome-stable"]

[phases.install]
dependsOn = ["setup"]
cmd = "npm install --include=dev --no-audit --no-fund && mkdir -p /tmp/.config /tmp/.local/share /tmp/.cache /tmp/chrome-user-data /tmp/chrome-data /tmp/chrome-cache /tmp/chrome-crashes"

[phases.build]
dependsOn = ["install"]

[variables]
NODE_ENV = "production"
NPM_CONFIG_TIMEOUT = "600000"
NPM_CONFIG_MAXSOCKETS = "3"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"
CHROME_BIN = "/usr/bin/google-chrome-stable"
NODE_OPTIONS = "--max-old-space-size=256"
HOME = "/tmp"
XDG_CONFIG_HOME = "/tmp/.config"
XDG_DATA_HOME = "/tmp/.local/share"
XDG_CACHE_HOME = "/tmp/.cache"
TMPDIR = "/tmp"
TEMP = "/tmp"
TMP = "/tmp"

[providers.node]
version = "18"

[build]
cmd = "npm run build"

[start]
cmd = "./start.sh"
