[phases.setup]
dependsOn = []
nixPkgs = ["chromium"]

[phases.install]
dependsOn = ["setup"]
cmd = "npm install --include=dev --no-audit --no-fund"

[phases.build]
dependsOn = ["install"]

[variables]
NODE_ENV = "production"
NPM_CONFIG_TIMEOUT = "600000"
NPM_CONFIG_MAXSOCKETS = "3"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*/bin/chromium"
NODE_OPTIONS = "--max-old-space-size=256"

[providers.node]
version = "18"

[build]
cmd = "npm run build:railway"

[start]
cmd = "node --max-old-space-size=256 --expose-gc dist/index.js"
