[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[env]
NODE_ENV = "production"
TOKEN = "bananalemon"
BROWSER_TIMEOUT = "45000"
MAX_CONCURRENT_SESSIONS = "1"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "30"
ENABLE_METRICS = "true"
LOG_LEVEL = "info"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
